#!/bin/sh

remaps &
picom &
dunst &
picom &
unclutter &
.config/screenlayout/default.sh &
xrdb ~/.config/colors/current.Xresources
setbg &
lxsession -s bspwm -e bspwm &

# debugging 
# sudo sysctl kernel.sysrq=1 
