#!/bin/sh
bspc rule -r "*"

wmname LG3D

startup &
sxhkd &
~/.config/polybar/launch.sh &

# xset r rate 300 50 &
# xrdb ~/.config/colors/current.Xresources
# xsetroot -cursor_name left_ptr

if [ "$(bspc query -M | wc -l)" -eq "2" ]; then
  bspc monitor eDP1  -d small
  bspc monitor HDMI2 -d main-1 main-2 3 4 5 trash 7 8 9
  ~/.config/polybar/launch2.sh &
else
  bspc monitor -d main-1 main-2 3 4 5 thrash 7 8 chat music
  ~/.config/polybar/launch.sh &
fi

bspc config border_width            3
bspc config window_gap              5

bspc config split_ratio             0.60
bspc config automatic_scheme        longest_side
bspc config focus_follows_pointer   true

bspc config pointer_modifer mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


# Border colors:
color_normal_border="#666666"
color_active_border="#666666"
color_focused_border="#ebcb8b"
color_presel_feedback="#888888"

bspc config normal_border_color $color_normal_border
bspc config active_border_color $color_active_border
bspc config focused_border_color $color_focused_border
bspc config presel_feedback_color $color_presel_feedback

bspc subscribe monitor | while read -r line; do
  case $line in
      monitor_add*|monitor_geometry*)
        if [ "$(bspc query -M | wc -l)" -eq "2" ]; then
          bspc monitor  eDP1  -d small
          bspc monitor  DP1 -d main-1 main-2 3 4 5 trash 7 8 9
          # bspc monitor  HDMI2 -d main-1 main-2 3 4 5 trash 7 8 9
          ~/.config/polybar/launch2.sh &
        else
          bspc monitor -d main-1 main-2 3 4 5 thrash 7 8 chat music
          ~/.config/polybar/launch.sh &
        fi
        ;;
      *)
      ;;
  esac
done &

